<?php

namespace App\Repository;

/**
 * AuthorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorityRepository extends \Doctrine\ORM\EntityRepository
{
}
