<?php

namespace App\Repository;

/**
 * BusinessSectorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BusinessSectorRepository extends \Doctrine\ORM\EntityRepository
{
}
