<?php

namespace App\Repository;

/**
 * ContactGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
