<?php

namespace App\Repository;

/**
 * EducationTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EducationTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
