<?php

namespace App\Repository;

/**
 * EmploymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmploymentRepository extends \Doctrine\ORM\EntityRepository
{
}
