<?php

namespace App\Repository;

/**
 * EventCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventCollectionRepository extends \Doctrine\ORM\EntityRepository
{
}
