<?php

namespace App\Repository;

/**
 * FinancialSupportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinancialSupportRepository extends \Doctrine\ORM\EntityRepository
{
}
