<?php

namespace App\Repository;

/**
 * GeographicRegionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GeographicRegionRepository extends \Doctrine\ORM\EntityRepository
{
}
