<?php

namespace App\Repository;

/**
 * InboxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InboxRepository extends \Doctrine\ORM\EntityRepository
{
}
