<?php

namespace App\Repository;

/**
 * InteractiveGraphicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InteractiveGraphicRepository extends \Doctrine\ORM\EntityRepository
{
}
