<?php

namespace App\Repository;

/**
 * Local Workgroup Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalWorkgroupRepository extends \Doctrine\ORM\EntityRepository
{
}
