<?php

namespace App\Repository;

/**
 * ProjectCollectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectCollectionRepository extends \Doctrine\ORM\EntityRepository
{
}
