<?php

namespace App\Repository;

/**
 * StintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StintRepository extends \Doctrine\ORM\EntityRepository
{
}
